=== iigokingii/TPvI_labs/labs/lab3/lab3/xmlFiles/info.xsd
<?xml version = "1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:simpleType name="Enum">
        <xsd:restriction>
            <xsd:enumeration value="first"></xsd:enumeration>
            <xsd:enumeration value="second"></xsd:enumeration>
            <xsd:enumeration value="third"></xsd:enumeration>
            <xsd:enumeration value="fourth"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="student">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"></xsd:element>
            <xsd:element name="surname" type="xsd:string"></xsd:element>
            <xsd:element name="averageScore" type="xsd:double"></xsd:element>
            <xsd:element name="budgetForm" type="xsd:boolean"></xsd:element>
            <xsd:element name="course" type="Enum"></xsd:element>
            <xsd:element name="Speciality" type="xsd:string"></xsd:element>
            <xsd:element name="age" type="xsd:integer"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="Dean">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="list">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Student" type="student"></xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== iigokingii/TPvI_labs/labs/lab3/lab3/xmlFiles/info.xml
<Dean xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="info.xsd">
    <list>
        <Student>
            <name>1</name>
            <surname>2</surname>
            <averageScore>2.4</averageScore>
            <budgetForm>true</budgetForm>
            <course>first</course>
            <Speciality>POIT</Speciality>
            <age>22</age>
        </Student>
        <Student>
            <name>2</name>
            <surname>3</surname>
            <averageScore>4.4</averageScore>
            <budgetForm>false</budgetForm>
            <course>third</course>
            <Speciality>POIT</Speciality>
            <age>20</age>
        </Student>
        <Student>
            <name>qwe</name>
            <surname>sasda</surname>
            <averageScore>9.4</averageScore>
            <budgetForm>false</budgetForm>
            <course>fourth</course>
            <Speciality>ISIT</Speciality>
            <age>21</age>
        </Student>
    </list>
</Dean>
